[project]
name = "collator"
version = "0.1.0"
description = "Collates transcriptions for PTA"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docopt==0.6.2",
    "ipykernel>=6.29.5",
    "pandas>=2.3.1",
]

[project.optional-dependencies]
dev = [
    "pytest"
]

[project.scripts]
collator = "collator:main"

[tool.setuptools]
include-package-data = true
package-dir = { "" = "." }


[tool.setuptools.packages.find]
where = ["."]
exclude = ["data"]
